# frozen_string_literal: true

module Engine
  module Game
    module G18IrePL
      module Entities
        COMPANIES = [
          {
            name: 'Dalkey Atmospheric Railway',
            value: 20,
            revenue: 5,
            desc: 'No company can build in the Wicklow hex until this company is either bought by'\
                  ' any company or closed.',
            sym: 'DAR',
            abilities: [{ type: 'blocks_hexes', owner_type: 'player', hexes: ['J14'] }],
          },
          {
            name: 'Wrocław-Oława Railway',
            value: 40,
            revenue: 10,
            desc: 'Once per game, in any moment of the laying or upgrading track step of its operating round,'\
                  ' owning company may lay an extra yellow track in either Zielona Góra (B10), Wałbrzych (B12),'\
                  ' Bielsko-Biała (F18) or Zakopane (G19), following normal track laying rules.',
            sym: 'WOR',
            abilities: [
              {
                type: 'tile_lay',
                hexes: %w[B10 B12 F18 G19],
                tiles: [],
                when: 'track',
                owner_type: 'corporation',
                free: true,
                count: 1,
              },
            ],
          },
          {
            name: 'Donegal Railway',
            value: 30,
            revenue: 7,
            desc: 'The owning Corporation can place two connected narrow gauge yellow tiles in the Donegal'\
                  ' hex and one adjacent hex. This action closes the company.',
            sym: 'DR',
            abilities: [
              {
                type: 'tile_lay',
                hexes: %w[F4 F2 E3 E5 G3 G5],
                tiles: %w[IR5 77 78 79],
                when: 'track',
                owner_type: 'corporation',
                count: 2,
                must_lay_together: true,
                must_lay_all: true,
                closed_when_used_up: true,
              },
            ],
          },
          {
            name: 'Board of Works',
            value: 40,
            revenue: 9,
            desc: 'The owning Corporation can place a yellow tile without payment of terrain costs.'\
                  ' The company closes once this ability has been used twice.',
            sym: 'BoW',
            abilities: [
              {
                type: 'tile_lay',
                hexes: [],
                tiles: [],
                when: 'track',
                owner_type: 'corporation',
                consume_tile_lay: true,
                free: true,
                count: 2,
                closed_when_used_up: true,
              },
            ],
          },
          {
            name: 'City of Dublin Steam Packet Company',
            value: 45,
            revenue: 10,
            desc: 'The owning Corporation can place the +£10 token on any port (Belfast, Londonderry or Rosslare).'\
                  ' This action closes the company, but the Corporation adds £10 to the' \
                  " port's revenue until the end of the game.",
            sym: 'CDSPC',
            abilities: [
              {
                type: 'assign_hexes',
                when: 'owning_corp_or_turn',
                hexes: %w[J4 G1 I19],
                count: 1,
                owner_type: 'corporation',
              },
              {
                type: 'assign_corporation',
                when: 'any',
                count: 1,
                owner_type: 'corporation',
              },
            ],
          },
          {
            name: 'Tralee & Dingle Railway',
            value: 50,
            revenue: 10,
            desc: 'The owning Corporation can place two connected narrow gauge yellow tiles in the'\
                  ' Tralee and Dingle hexes. This action closes the company.',
            sym: 'TDR',
            abilities: [
              {
                type: 'tile_lay',
                hexes: %w[A19 B18],
                tiles: ['IR5'],
                when: 'track',
                owner_type: 'corporation',
                count: 2,
                must_lay_together: true,
                must_lay_all: true,
                closed_when_used_up: true,
              },
            ],
          },
          {
            name: 'Drumglass Colliery Railway',
            value: 60,
            revenue: 12,
            desc: 'No Corporation can build in the DCR hex (H4) until this company is bought by any Corporation'\
                  ' or closed. The owning Corporation may place a yellow tile, subject to normal track laying rules,'\
                  ' on that hex (H4) without using a tile action or paying terrain costs.',
            sym: 'DCR',
            abilities: [
              {
                type: 'blocks_hexes',
                owner_type: 'player',
                hexes: ['H4'],
              },
              {
                type: 'tile_lay',
                hexes: ['H4'],
                tiles: [],
                when: 'owning_corp_or_turn',
                owner_type: 'corporation',
                free: true,
                count: 1,
              },
            ],
          },
          {
            name: 'Trans-Atlantic Steam Packet Station',
            value: 75,
            revenue: 15,
            desc: 'The owning Corporation can place the +£20 token on Galway. This action closes the company,'\
                  " but the Corporation adds £20 to the city's revenue until the end of the game.",
            sym: 'TASPS',
            abilities: [
              {
                type: 'assign_hexes',
                when: 'owning_corp_or_turn',
                hexes: %w[C13],
                count: 1,
                owner_type: 'corporation',
              },
              {
                type: 'assign_corporation',
                when: 'any',
                count: 1,
                owner_type: 'corporation',
              },
            ],
          },
          {
            name: 'River Shannon Shipping Co',
            value: 80,
            revenue: 10,
            desc: 'The owning Corporation controls a river link between Dromod and Limerick and adds the value of the'\
                  ' other city to one train ending at either Dromod or Limerick.',
            sym: 'RSSC',
          },
          {
            name: 'William Dargan Esq.',
            value: 90,
            revenue: 10,
            desc: 'The owning Corporation can upgrade a second track tile during each'\
                  " OR at a cost of £30 from the Corporation's Treasury.",
            sym: 'WDE',
          },
          {
            name: 'The Irish Mail',
            value: 110,
            revenue: 20,
            desc: 'The owning Corporation can place an off-board location tile adjacent'\
                  ' to one of: Londonderry, Kingstown, or Waterford. This action closes the company,'\
                  ' but any Corporation may run to the tile for the rest of the game.',
            sym: 'TIM',
            abilities: [
              {
                type: 'tile_lay',
                hexes: %w[F0 H0 G-1 J12 G21 H20],
                tiles: ['IM'],
                when: 'track',
                owner_type: 'corporation',
                count: 1,
                closed_when_used_up: true,
              },
            ],
          },
          {
            name: 'Dublin & Kingstown Railway',
            value: 120,
            revenue: 0,
            desc: 'The owner of this company: Takes the DKR directorship; sets the share'\
                  ' price at half bid; places a 2H-Train on the charter; places the winning bid'\
                  ' in the DKR treasury less the cost of the train and discards this card.',
            sym: 'DK',
            abilities: [
            { type: 'close', when: 'bought_train', corporation: 'DKR' },
            { type: 'no_buy' },
            { type: 'shares', shares: 'DKR_0' },
            ],
          },
      ].freeze

        CORPORATIONS = [
          {
            float_percent: 20,
            sym: 'CMK',
            name: 'Centralna Magistrala Kolejowa',
            logo: '18_ireland/GSWR',
            tokens: [0, 40, 40, 40],
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            always_market_price: true,
            color: 'red',
            reservation_color: nil,
            type: 'major',
            max_ownership_percent: 60,
          },
          {
            float_percent: 20,
            sym: 'PKP',
            name: 'Polskie Koleje Państwowe',
            logo: '18_ireland/GNRI',
            tokens: [0, 40, 40, 40],
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            always_market_price: true,
            color: 'blue',
            reservation_color: nil,
            type: 'major',
            max_ownership_percent: 60,
          },
          {
            float_percent: 20,
            sym: 'KWW',
            name: 'Kolej Warszawsko-Wiedeńska',
            logo: '18_ireland/DSER',
            tokens: [0, 40, 40, 40],
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            always_market_price: true,
            color: 'purple',
            reservation_color: nil,
            type: 'major',
            max_ownership_percent: 60,
          },
          {
            float_percent: 20,
            sym: 'TKG',
            name: 'Towarzystwo Kolei Górnośląskiej',
            logo: '18_ireland/MGWR',
            tokens: [0, 40, 40, 40],
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            always_market_price: true,
            color: 'orange',
            reservation_color: nil,
            type: 'major',
            max_ownership_percent: 60,
          },
          {
            float_percent: 20,
            sym: 'LHS',
            name: 'Linia Hutniczo-Siarkowa',
            logo: '18_ireland/MRNCC',
            tokens: [0, 40, 40, 40],
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            always_market_price: true,
            color: 'green',
            reservation_color: nil,
            type: 'major',
            max_ownership_percent: 60,
          },
          {
            float_percent: 20,
            sym: 'MW',
            name: 'Magistrala Węglowa',
            logo: '18_ireland/WLWR',
            tokens: [0, 40, 40, 40],
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            always_market_price: true,
            color: 'yellow',
            reservation_color: nil,
            type: 'major',
            max_ownership_percent: 60,
          },
          # minors
          {
            float_percent: 40,
            sym: 'M1',
            name: 'Minor 1',
            logo: '18_ire_pl/M1',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'white',
            reservation_color: nil,
            type: 'minor',
            coordinates: 'D2',
          },
          {
            float_percent: 40,
            sym: 'M2',
            name: 'Minor 2',
            logo: '18_ire_pl/M2',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'white',
            reservation_color: nil,
            type: 'minor',
            coordinates: 'E3',
          },
          {
            float_percent: 40,
            sym: 'M3',
            name: 'Minor 3',
            logo: '18_ire_pl/M3',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'white',
            reservation_color: nil,
            type: 'minor',
            coordinates: 'A5',
          },
          {
            float_percent: 40,
            sym: 'M4',
            name: 'Minor 4',
            logo: '18_ire_pl/M4',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'white',
            reservation_color: nil,
            type: 'minor',
            coordinates: 'G5',
          },
          {
            float_percent: 40,
            sym: 'M5',
            name: 'Minor 5',
            logo: '18_ire_pl/M5',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'white',
            reservation_color: nil,
            type: 'minor',
            coordinates: 'D6',
          },
          {
            float_percent: 40,
            sym: 'M6',
            name: 'Minor 6',
            logo: '18_ire_pl/M6',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'white',
            reservation_color: nil,
            type: 'minor',
            coordinates: 'K7',
          },
          {
            float_percent: 40,
            sym: 'M7',
            name: 'Minor 7',
            logo: '18_ire_pl/M7',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'white',
            reservation_color: nil,
            type: 'minor',
            coordinates: 'C9',
          },
          {
            float_percent: 40,
            sym: 'M8',
            name: 'Minor 8',
            logo: '18_ire_pl/M8',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'white',
            reservation_color: nil,
            type: 'minor',
            coordinates: 'H10',
          },
          {
            float_percent: 40,
            sym: 'M9',
            name: 'Minor 9',
            logo: '18_ire_pl/M9',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'white',
            reservation_color: nil,
            type: 'minor',
            coordinates: 'F12',
          },
          {
            float_percent: 40,
            sym: 'M10',
            name: 'Minor 10',
            logo: '18_ire_pl/M10',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'white',
            reservation_color: nil,
            type: 'minor',
            coordinates: 'C13',
          },
          {
            float_percent: 40,
            sym: 'M11',
            name: 'Minor 11',
            logo: '18_ire_pl/M11',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'white',
            reservation_color: nil,
            type: 'minor',
            coordinates: 'J14',
          },
          {
            float_percent: 40,
            sym: 'M12',
            name: 'Minor 12',
            logo: '18_ire_pl/M12',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'white',
            reservation_color: nil,
            type: 'minor',
            coordinates: 'F16',
          },
          {
            float_percent: 40,
            sym: 'M13',
            name: 'Minor 13',
            logo: '18_ire_pl/M13',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'white',
            reservation_color: nil,
            type: 'minor',
            coordinates: 'G17',
          },
          {
            float_percent: 40,
            sym: 'M14',
            name: 'Minor 14',
            logo: '18_ire_pl/M14',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'white',
            reservation_color: nil,
            type: 'minor',
            coordinates: 'I17',
          },
        ].freeze
      end
    end
  end
end
