# frozen_string_literal: true

module Engine
  module Game
    module G18IrePL
      module Entities
        COMPANIES = [
          {
            name: 'Industrialisation of Łódź',
            value: 20,
            revenue: 5,
            desc: 'Owning corporation may place a +20 marker in Łódź (F12). For all corporations the value of the city is increased by 20.'\
                  ' If the marker still isn\'t placed when at the start of brown phase, it is placed immediately.'\
                  ' The marker isn\'t removed when Industrialisation of Łódź closes or when the hex is upgraded.',
            sym: 'IOL',
            abilities: [
              {
                type: 'assign_hexes',
                when: 'tile_lay',
                hexes: ['F12'],
                count: 1,
                owner_type: 'corporation',
              },
              {
                type: 'assign_corporation',
                when: 'any',
                count: 1,
                owner_type: 'corporation',
              },
            ],
          },
          {
            name: 'Wrocław-Oława Railway',
            value: 40,
            revenue: 10,
            desc: 'Once per game, in any moment of the laying or upgrading track step of its operating round,'\
                  ' owning corporation may lay an extra yellow track in either Zielona Góra (B10), Wałbrzych (B12),'\
                  ' Bielsko-Biała (F18) or Zakopane (G19), following normal track laying rules.',
            sym: 'WOR',
            abilities: [
              {
                type: 'tile_lay',
                hexes: %w[B10 B12 F18 G19],
                tiles: [],
                when: 'track',
                owner_type: 'corporation',
                free: true,
                count: 1,
              },
            ],
          },
          {
            name: 'Bridge Company',
            value: 55,
            revenue: 10,
            desc: 'Owning corporation ignores river costs until the end of the game.',
            sym: 'BC',
            abilities: [
              {
                type: 'tile_discount',
                owner_type: 'corporation',
                discount: 30,
                terrain: 'water',
              },
              {
                type: 'close',
                on_phase: 'never',
                owner_type: 'corporation',
              },
              {
                type: 'revenue_change',
                revenue: 0,
                on_phase: 'Brown',
                owner_type: 'corporation',
              },
            ],
          },
          {
            name: 'Wilhelmsbahn',
            value: 70,
            revenue: 10,
            desc: 'When thisis purchased by a corporation, that corporation may immediately lay a yellow track, following normal track laying rules.'\
                  ' Once per game, in any moment of the laying or upgrading track step of its operating round, owning corporation may pay 20zł to lay'\
                  ' an extra yellow track, following normal track laying rules.'\
                  ' It is possible to lay those two additional yellow tracks in one round. It is possible to upgrade a track laid by this power in the '\
                  ' same round (using normal laying or upgrading track action).',
            sym: 'WB',
            abilities: [],
          },
          {
            name: 'Baltic Shipping',
            value: 100,
            revenue: 15,
            desc: 'During the aying or upgrading track step of its operating round, in addition to the normal track lay or upgrade, owning crporation'\
                  ' may place a 50 marker near one of the ports (A3, C1, F2). The corporation is not required to be connected to the port. This forms an exclusive'\
                  ' revenue center worth 50 that is accessible for that corporation only. The corporation may no longer access the regular port worth 10 in the same'\
                  ' hex.'\
                  ' The corporation may access the port with only one train per operating round, even if there are two different connections leading to the port.'\
                  ' Other corprorations may still access the regular port with two trains.',
            sym: 'BS',
            abilities: [
              {
                type: 'assign_hexes',
                when: 'tile_lay',
                hexes: %w[A3 C1 F2],
                count: 1,
                owner_type: 'corporation',
              },
              {
                type: 'assign_corporation',
                when: 'any',
                count: 1,
                owner_type: 'corporation',
              },
            ],
          },
          {
            name: 'Warszawa-Radom Railway',
            value: 120,
            revenue: 0,
            desc: 'The owner of this company takes the M8 directorship. The winning bid is put into the M8 treasury. M8 share price is the highest'\
                  ' yellow par value that is not more than half the bid.'\
                  ' This private company closes immediately.',
            sym: 'WRR',
            abilities: [
              { type: 'close', when: 'par', 'corporation': 'M8' },
              { type: 'no_buy' },
              { type: 'shares', shares: 'M8_0' },
            ],
          },
      ].freeze

        CORPORATIONS = [
          {
            float_percent: 20,
            sym: 'CMK',
            name: 'Centralna Magistrala Kolejowa',
            logo: '18_ire_pl/CMK',
            simple_logo: '18_ire_pl/CMK.alt',
            tokens: [0, 40, 40, 40],
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            always_market_price: true,
            color: 'red',
            reservation_color: nil,
            type: 'major',
            max_ownership_percent: 60,
          },
          {
            float_percent: 20,
            sym: 'PKP',
            name: 'Polskie Koleje Państwowe',
            logo: '18_ire_pl/PKP',
            logo: '18_ire_pl/PKP.alt',
            tokens: [0, 40, 40, 40],
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            always_market_price: true,
            color: 'blue',
            reservation_color: nil,
            type: 'major',
            max_ownership_percent: 60,
          },
          {
            float_percent: 20,
            sym: 'KWW',
            name: 'Kolej Warszawsko-Wiedeńska',
            logo: '18_ire_pl/KWW',
            logo: '18_ire_pl/KWW.alt',
            tokens: [0, 40, 40, 40],
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            always_market_price: true,
            color: 'purple',
            reservation_color: nil,
            type: 'major',
            max_ownership_percent: 60,
          },
          {
            float_percent: 20,
            sym: 'TKG',
            name: 'Towarzystwo Kolei Górnośląskiej',
            logo: '18_ire_pl/TKG',
            logo: '18_ire_pl/TKG.alt',
            tokens: [0, 40, 40, 40],
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            always_market_price: true,
            color: 'orange',
            reservation_color: nil,
            type: 'major',
            max_ownership_percent: 60,
          },
          {
            float_percent: 20,
            sym: 'LHS',
            name: 'Linia Hutniczo-Siarkowa',
            logo: '18_ire_pl/LHS',
            logo: '18_ire_pl/LHS.alt',
            tokens: [0, 40, 40, 40],
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            always_market_price: true,
            color: 'green',
            reservation_color: nil,
            type: 'major',
            max_ownership_percent: 60,
          },
          {
            float_percent: 20,
            sym: 'MW',
            name: 'Magistrala Węglowa',
            logo: '18_ire_pl/MW',
            logo: '18_ire_pl/MW.alt',
            tokens: [0, 40, 40, 40],
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            always_market_price: true,
            color: 'yellow',
            text_color: 'black',
            reservation_color: nil,
            type: 'major',
            max_ownership_percent: 60,
          },
          # minors
          {
            float_percent: 40,
            sym: 'M1',
            name: 'Minor 1',
            logo: '18_ire_pl/M1',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'black',
            reservation_color: nil,
            type: 'minor',
            coordinates: 'D2',
          },
          {
            float_percent: 40,
            sym: 'M2',
            name: 'Minor 2',
            logo: '18_ire_pl/M2',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'black',
            reservation_color: nil,
            type: 'minor',
            coordinates: 'E3',
            abilities: [
              {
                type: 'tile_lay',
                discount: 30,
                description: 'Ignores river cost in the home hex.',
                desc_detail: 'Ignores river cost in E3.',
                passive: true,
                when: 'track',
                hexes: ['E3'],
                tiles: ['5', '6', '57'],
              },
            ],
          },
          {
            float_percent: 40,
            sym: 'M3',
            name: 'Minor 3',
            logo: '18_ire_pl/M3',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'black',
            reservation_color: nil,
            type: 'minor',
            coordinates: 'A5',
          },
          {
            float_percent: 40,
            sym: 'M4',
            name: 'Minor 4',
            logo: '18_ire_pl/M4',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'black',
            reservation_color: nil,
            type: 'minor',
            coordinates: 'G5',
            abilities: [
              {
                type: 'tile_lay',
                discount: 30,
                description: 'Ignores river cost in the home hex.',
                desc_detail: 'Ignores river cost in G5.',
                passive: true,
                when: 'track',
                hexes: ['G5'],
                tiles: ['5', '6', '57'],
              },
            ],
          },
          {
            float_percent: 40,
            sym: 'M5',
            name: 'Minor 5',
            logo: '18_ire_pl/M5',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'black',
            reservation_color: nil,
            type: 'minor',
            coordinates: 'D6',
          },
          {
            float_percent: 40,
            sym: 'M6',
            name: 'Minor 6',
            logo: '18_ire_pl/M6',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'black',
            reservation_color: nil,
            type: 'minor',
            coordinates: 'K7',
            abilities: [
              {
                type: 'tile_lay',
                discount: 30,
                description: 'Ignores river cost in the home hex.',
                desc_detail: 'Ignores river cost in K7.',
                passive: true,
                when: 'track',
                hexes: ['K7'],
                tiles: ['5', '6', '57'],
              },
            ],
          },
          {
            float_percent: 40,
            sym: 'M7',
            name: 'Minor 7',
            logo: '18_ire_pl/M7',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'black',
            reservation_color: nil,
            type: 'minor',
            coordinates: 'C9',
          },
          {
            float_percent: 40,
            sym: 'M8',
            name: 'Minor 8',
            logo: '18_ire_pl/M8',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'black',
            reservation_color: nil,
            type: 'minor',
            coordinates: 'H10',
          },
          {
            float_percent: 40,
            sym: 'M9',
            name: 'Minor 9',
            logo: '18_ire_pl/M9',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'black',
            reservation_color: nil,
            type: 'minor',
            coordinates: 'F12',
          },
          {
            float_percent: 40,
            sym: 'M10',
            name: 'Minor 10',
            logo: '18_ire_pl/M10',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'black',
            reservation_color: nil,
            type: 'minor',
            coordinates: 'C13',
          },
          {
            float_percent: 40,
            sym: 'M11',
            name: 'Minor 11',
            logo: '18_ire_pl/M11',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'black',
            reservation_color: nil,
            type: 'minor',
            coordinates: 'J14',
          },
          {
            float_percent: 40,
            sym: 'M12',
            name: 'Minor 12',
            logo: '18_ire_pl/M12',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'black',
            reservation_color: nil,
            type: 'minor',
            coordinates: 'F16',
          },
          {
            float_percent: 40,
            sym: 'M13',
            name: 'Minor 13',
            logo: '18_ire_pl/M13',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'black',
            reservation_color: nil,
            type: 'minor',
            coordinates: 'G17',
            abilities: [
              {
                type: 'tile_lay',
                discount: 30,
                description: 'Ignores river cost in the home hex.',
                desc_detail: 'Ignores river cost in G17.',
                passive: true,
                when: 'track',
                hexes: ['G17'],
                tiles: ['5', '6', '57'],
              },
            ],
          },
          {
            float_percent: 40,
            sym: 'M14',
            name: 'Minor 14',
            logo: '18_ire_pl/M14',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'black',
            reservation_color: nil,
            type: 'minor',
            coordinates: 'I17',
            abilities: [
              {
                type: 'tile_lay',
                discount: 30,
                description: 'Ignores river cost in the home hex.',
                desc_detail: 'Ignores river cost in I17.',
                passive: true,
                when: 'track',
                hexes: ['I17'],
                tiles: ['5', '6', '57'],
              },
            ],
          },
          {
            float_percent: 40,
            sym: 'MA',
            name: 'Minor A',
            logo: '18_ire_pl/MA',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'black',
            reservation_color: nil,
            type: 'minor',
          },
          {
            float_percent: 40,
            sym: 'MB',
            name: 'Minor B',
            logo: '18_ire_pl/MB',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'black',
            reservation_color: nil,
            type: 'minor',
          },
        ].freeze
      end
    end
  end
end
