# frozen_string_literal: true

module Engine
    module Game
      module G1839
        module Map
          TILES = {
            '1' => 1,
            '2' => 1,
            '3' => 2,
            '4' => 2,
            '5' => 4,
            '6' => 4,
            '7' => 5,
            '8' => 10,
            '9' => 10,
            '14' => 4,
            '15' => 4,
            '16' => 1,
            '17' => 1,
            '18' => 1,
            '19' => 1,
            '20' => 1,
            '21' => 1,
            '22' => 1,
            '80' => 4,
            '81' => 4,
            '82' => 4,
            '83' => 4,
            '55' => 1,
            '56' => 1,
            '57' => 4,
            '58' => 2,
            '69' => 1,
            '619' => 4,
            '625' => 1,
            '626' => 1,
            '630' => 1,
            '631' => 1,
            '632' => 1,
            '633' => 1,
            'B13' => {
              'count' => 1,
              'color' => 'yellow',
              'code' => 'city=revenue:30;path=a:0,b:_0;path=a:2,b:_0;path=a:4,b:_0;label=B;upgrade=cost:80,terrain:water',
            },
            'B206' => {
              'count' => 1,
              'color' => 'yellow',
              'code' => 'city=revenue:30;path=a:0,b:_0;path=a:1,b:_0;path=a:4,b:_0;label=B;upgrade=cost:80,terrain:water',
            },
            'H13' => {
              'count' => 1,
              'color' => 'yellow',
              'code' => 'city=revenue:30;path=a:0,b:_0;path=a:4,b:_0;label=H;upgrade=cost:80,terrain:water',
            },
            'L5' => {
              'count' => 2,
              'color' => 'yellow',
              'code' => 'city=revenue:30,loc:5.5;city=revenue:0;path=a:0,b:_0;path=a:5,b:_0;label=OO',
            },
            'L6' => {
              'count' => 2,
              'color' => 'yellow',
              'code' => 'city=revenue:30;city=revenue:0;path=a:0,b:_0;path=a:4,b:_0;label=OO',
            },
            'L57' => {
              'count' => 2,
              'color' => 'yellow',
              'code' => 'city=revenue:30;city=revenue:0,loc:1.5;path=a:0,b:_0;path=a:3,b:_0;label=OO',
            },
            'R13' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:30;path=a:0,b:_0;path=a:4,b:_0;label=R;upgrade=cost:80,terrain:water',
            },
            'U13' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:30;path=a:0,b:_0;path=a:4,b:_0;label=U;upgrade=cost:80,terrain:water',
            },
            'A425' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:60;city=revenue:60,loc:4;path=a:0,b:_0;path=a:1,b:_0;path=a:2,b:_0;'\
                        'path=a:3,b:_1;path=a:4,b:_1;path=a:5,b:_1;label=A',
            },
            'B121' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:40,slots:2;path=a:0,b:_0;path=a:1,b:_0;path=a:2,b:_0;path=a:4,b:_0;label=B;upgrade=cost:80,terrain:water',
            },
            'B122' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:40,slots:2;path=a:0,b:_0;path=a:1,b:_0;path=a:4,b:_0;path=a:5,b:_0;label=B;upgrade=cost:80,terrain:water',
            },
            # 'B123' => {
            #   'count' => 1,
            #   'color' => 'green',
            #   'code' => 'city=revenue:40,slots:2;path=a:0,b:_0;path=a:1,b:_0;path=a:3,b:_0;path=a:4,b:_0;label=B;upgrade=cost:80,terrain:water',
            # },
            'H121' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:40,slots:2;path=a:0,b:_0;path=a:2,b:_0;path=a:4,b:_0;label=H;upgrade=cost:80,terrain:water',
            },
            'L118' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:40,loc:5.5;city=revenue:40,loc:3.5;path=a:0,b:_0;path=a:5,b:_0;path=a:3,b:_1;path=a:4,b:_1;label=OO',
            },
            'L212' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:50,loc:5.5;city=revenue:50,loc:2.5;path=a:0,b:_0;path=a:5,b:_0;path=a:2,b:_1;path=a:3,b:_1;label=OO',
            },
            'L35' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:40;city=revenue:40;path=a:0,b:_0;path=a:2,b:_0;path=a:1,b:_1;path=a:5,b:_1;label=OO',
            },
            'L36' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:50;city=revenue:50;path=a:0,b:_0;path=a:4,b:_0;path=a:1,b:_1;path=a:3,b:_1;label=OO',
            },
            'L64' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:40;city=revenue:40,loc:3.5;path=a:0,b:_0;path=a:2,b:_0;path=a:3,b:_1;path=a:4,b:_1;label=OO',
            },
            'L65' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:40;city=revenue:40,loc:4.5;path=a:0,b:_0;path=a:2,b:_0;path=a:4,b:_1;path=a:5,b:_1;label=OO',
            },
            'L66' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:40;city=revenue:40,loc:1.5;path=a:0,b:_0;path=a:3,b:_0;path=a:1,b:_1;path=a:2,b:_1;label=OO',
            },
            'L67' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:40;city=revenue:40;path=a:0,b:_0;path=a:3,b:_0;path=a:1,b:_1;path=a:5,b:_1;label=OO',
            },
            'L68' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:40;city=revenue:40;path=a:0,b:_0;path=a:3,b:_0;path=a:2,b:_1;path=a:5,b:_1;label=OO',
            },
            'R121' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:40,slots:2;path=a:0,b:_0;path=a:2,b:_0;path=a:4,b:_0;label=R;upgrade=cost:80,terrain:water',
            },
            'R123' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:40,slots:2;path=a:0,b:_0;path=a:1,b:_0;path=a:2,b:_0;label=R;upgrade=cost:80,terrain:water',
            },
            'U121' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:40,slots:2;path=a:0,b:_0;path=a:2,b:_0;path=a:4,b:_0;label=U;upgrade=cost:80,terrain:water',
            },
          }.freeze

          LOCATION_NAMES = {
            'A4' => 'Great Britain',
            'A10' => 'London',
            'A12' => 'London shipping',
            'B3' => 'Le Havre',
            'B9' => 'Calais',
            'B11' => 'Dunkerque',
            'C16' => 'Netherlands',
            'D1' => 'Évreux',
            'D3' => 'Rouen',
            'D11' => 'Lille',
            'D15' => 'Gent',
            'D17' => 'Antwerpen',
            'E6' => 'Amiens',
            'E10' => 'Arras',
            'E16' => 'Mechelen',
            'F15' => 'Bruxelles',
            'G2' => 'Versailles',
            'G4' => 'Paris',
            'G10' => 'Saint-Quentin',
            'G14' => 'Charleroi',
            'H1' => 'Chartres',
            'H7' => 'Soissons',
            'H17' => 'Liège',
            'I2' => 'Centre & Bourgogne',
            'I8' => 'Reims',
            'I18' => 'Luxembourg',
          }.freeze

          HEXES = {
            white: {
              %w[A14 A18 B15 C14 C16 D17 E16 F9 F17 G6 H9 H19 I6 I10 I18 J13 K10 K14] => '',
              %w[D13 H15 J9 J11 J15 M14] => 'upgrade=cost:80,terrain:water',
              %w[D19 H13 I8 L3 N17] => 'city=revenue:0',
              %w[H5 I16 K6 K16 N15] => 'city=revenue:0;upgrade=cost:80,terrain:water',
              %w[B17 F19 G16 K12] => 'city=revenue:0;city=revenue:0;label=OO',
              %w[C18 E18 F7 H11 H17 I14] => 'town=revenue:0;town=revenue:0',
              %w[A16 D15 M16] => 'town=revenue:0',
              ['B13'] => 'city=revenue:0;border=edge:1,type:impassable',
              ['C12'] => 'town=revenue:0;border=edge:1,type:impassable;border=edge:2,type:impassable',
              ['E8'] => 'border=edge:3,type:impassable',
              ['E14'] => 'city=revenue:0;border=edge:0,type:impassable',
              ['F13'] => 'town=revenue:10;town=revenue:0;path=a:0,b:_0;'\
                         'border=edge:3,type:impassable;border=edge:4,type:impassable;border=edge:5,type:impassable',
              ['F15'] => 'upgrade=cost:80,terrain:water;border=edge:1,type:impassable',
              ['G8'] => 'city=revenue:0;label=H;stub=edge:4;upgrade=cost:80,terrain:water',
              ['G14'] => 'city=revenue:0;border=edge:2,type:impassable',
              ['G18'] => 'city=revenue:0;city=revenue:0;label=OO;upgrade=cost:80,terrain:water',
              ['H7'] => 'town=revenue:0;town=revenue:0;upgrade=cost:80,terrain:water',
              ['I12'] => 'city=revenue:0;label=U;upgrade=cost:80,terrain:water',
              ['J7'] => 'city=revenue:0;label=R;stub=edge:3;upgrade=cost:80,terrain:water;border=edge:5,type:impassable',
              ['K8'] => 'city=revenue:0;label=B;path=a:5,b:_0;stub=edge:3;upgrade=cost:80,terrain:water;border=edge:2,type:impassable',
            },
            yellow: {
              %w[L13 L17] => 'city=revenue:20;path=a:1,b:_0;path=a:4,b:_0',
              ['B11'] => 'path=a:0,b:4;border=edge:4,type:impassable;border=edge:5,type:impassable',
              ['B19'] => 'city=revenue:20,slots:2;path=a:0,b:_0;path=a:1,b:_0',
              ['C10'] => 'path=a:0,b:3;border=edge:4,type:impassable',
              ['D9'] => 'path=a:1,b:3;border=edge:0,type:impassable;border=edge:1,type:impassable;border=edge:5,type:impassable',
              ['G10'] => 'city=revenue:40;city=revenue:40;label=A;path=a:1,b:_0;path=a:5,b:_1;upgrade=cost:80,terrain:water',
              ['G12'] => 'path=a:1,b:3',
              ['L11'] => 'path=a:0,b:4',
              ['L15'] => 'path=a:1,b:4',
            },
            gray: {
              %w[M4 M10 O16] => 'town=revenue:10;path=a:2,b:_0;path=a:3,b:_0',
              ['B21'] => 'path=a:1,b:2;path=a:0,b:1',
              ['D7'] => 'town=revenue:10;path=a:4,b:_0;path=a:5,b:_0;border=edge:4,type:impassable',
              ['E10'] => 'city=revenue:40;path=a:0,b:_0;path=a:1,b:_0;path=a:2,b:_0;path=a:4,b:_0;border=edge:2,type:impassable',
              ['F21'] => 'town=revenue:10;path=a:0,b:_0;path=a:1,b:_0',
              ['G4'] => 'town=revenue:10;path=a:5,b:_0',
              ['I4'] => 'path=a:0,b:3;path=a:3,b:5',
              ['J3'] => 'path=a:0,b:3;path=a:0,b:4',
              ['J5'] => 'path=a:1,b:4;path=a:2,b:4',
              ['K2'] => 'path=a:0,b:3',
              ['K4'] => 'town=revenue:10;path=a:4,b:_0;path=a:5,b:_0',
              ['L5'] => 'town=revenue:10;path=a:1,b:2;path=a:0,b:_0;path=a:3,b:4;path=a:4,b:_0',
              ['L7'] => 'town=revenue:20;path=a:1,b:4;path=a:1,b:_0;path=a:3,b:_0',
              ['N13'] => 'town=revenue:10;path=a:3,b:_0;path=a:4,b:_0',
            },
            blue: {
              ['A20'] => 'offboard=revenue:yellow_20|brown_0|gray_100;path=a:0,b:_0;path=a:1,b:_0',
              ['D11'] => '',
              ['E12'] => 'offboard=revenue:yellow_20|brown_0|gray_10;path=a:1,b:_0;path=a:5,b:_0',
              ['F11'] => 'offboard=revenue:yellow_30|brown_0|gray_70;path=a:0,b:_0;path=a:5,b:_0',
              ['L1'] => 'offboard=revenue:yellow_30|brown_0|gray_100;path=a:3,b:_0;path=a:4,b:_0',
            },
            red: {
              ['L9'] => 'offboard=revenue:yellow_30|brown_20|gray_60;path=a:1,b:_0;path=a:2,b:_0;path=a:5,b:_0',
              ['M2'] => 'offboard=revenue:yellow_30|brown_20|gray_50;path=a:3,b:_0',
              ['O14'] => 'offboard=revenue:yellow_20|brown_30|gray_50;path=a:3,b:_0',
            },
            orange: {
              ['C20'] => 'offboard=revenue:yellow_20|brown_40|gray_60,groups:Bremen;path=a:1,b:_0;path=a:2,b:_0;path=a:3,b:_0;border=edge:5',
              ['D21'] => 'offboard=revenue:yellow_20|brown_40|gray_60,hide:1,groups:Bremen;path=a:1,b:_0;border=edge:2',
              ['G20'] => 'offboard=revenue:yellow_20|brown_40|gray_50;path=a:0,b:_0;path=a:1,b:_0;path=a:2,b:_0;path=a:3,b:_0',
              ['J17'] => 'offboard=revenue:0,groups:Ruhrgebied;icon=image:1839/ruhrgebied;path=a:0,b:_0;path=a:1,b:_0;path=a:2,b:_0;border=edge:5',
              ['K18'] => 'offboard=revenue:0,hide:1,groups:Ruhrgebied;path=a:1,b:_0;border=edge:2',
              ['L19'] => 'offboard=revenue:yellow_10|brown_20|gray_30;path=a:1,b:_0',
              ['N19'] => 'offboard=revenue:yellow_20|brown_40|gray_50;path=a:1,b:_0',
            }
          }.freeze
        end
      end
    end
  end