# frozen_string_literal: true

module Engine
    module Game
      module G1839
        module Map
          TILES = {
            '1' => 1,
            '2' => 1,
            '3' => 2,
            '4' => 2,
            '5' => 4,
            '6' => 4,
            '7' => 5,
            '8' => 10,
            '9' => 10,
            '14' => 4,
            '15' => 4,
            '16' => 1,
            '17' => 1,
            '18' => 1,
            '19' => 1,
            '20' => 1,
            '21' => 1,
            '22' => 1,
            '80' => 4,
            '81' => 4,
            '82' => 4,
            '83' => 4,
            '55' => 1,
            '56' => 1,
            '57' => 4,
            '58' => 2,
            '69' => 1,
            '544' => 1,
            '545' => 1,
            '546' => 1,
            '611' => 4,
            '619' => 4,
            '625' => 1,
            '626' => 1,
            '630' => 1,
            '631' => 1,
            '632' => 1,
            '633' => 1,
            'B13' => {
              'count' => 1,
              'color' => 'yellow',
              'code' => 'city=revenue:30;path=a:0,b:_0;path=a:2,b:_0;path=a:4,b:_0;label=B;upgrade=cost:80,terrain:water',
            },
            'B206' => {
              'count' => 1,
              'color' => 'yellow',
              'code' => 'city=revenue:30;path=a:0,b:_0;path=a:1,b:_0;path=a:4,b:_0;label=B;upgrade=cost:80,terrain:water',
            },
            'H13' => {
              'count' => 1,
              'color' => 'yellow',
              'code' => 'city=revenue:30;path=a:0,b:_0;path=a:4,b:_0;label=H;upgrade=cost:80,terrain:water',
            },
            'L5' => {
              'count' => 2,
              'color' => 'yellow',
              'code' => 'city=revenue:30,loc:5.5;city=revenue:0;path=a:0,b:_0;path=a:5,b:_0;label=OO',
            },
            'L6' => {
              'count' => 2,
              'color' => 'yellow',
              'code' => 'city=revenue:30;city=revenue:0;path=a:0,b:_0;path=a:4,b:_0;label=OO',
            },
            'L57' => {
              'count' => 2,
              'color' => 'yellow',
              'code' => 'city=revenue:30;city=revenue:0,loc:1.5;path=a:0,b:_0;path=a:3,b:_0;label=OO',
            },
            'R13' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:30;path=a:0,b:_0;path=a:4,b:_0;label=R;upgrade=cost:80,terrain:water',
            },
            'U13' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:30;path=a:0,b:_0;path=a:4,b:_0;label=U;upgrade=cost:80,terrain:water',
            },
            'A425' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:60;city=revenue:60,loc:4;path=a:0,b:_0;path=a:1,b:_0;path=a:2,b:_0;'\
                        'path=a:3,b:_1;path=a:4,b:_1;path=a:5,b:_1;label=A;upgrade=cost:80,terrain:water',
            },
            'B121' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:40,slots:2;path=a:0,b:_0;path=a:1,b:_0;path=a:2,b:_0;path=a:4,b:_0;label=B;upgrade=cost:80,terrain:water',
            },
            'B122' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:40,slots:2;path=a:0,b:_0;path=a:1,b:_0;path=a:4,b:_0;path=a:5,b:_0;label=B;upgrade=cost:80,terrain:water',
            },
            # 'B123' => {
            #   'count' => 1,
            #   'color' => 'green',
            #   'code' => 'city=revenue:40,slots:2;path=a:0,b:_0;path=a:1,b:_0;path=a:3,b:_0;path=a:4,b:_0;label=B;upgrade=cost:80,terrain:water',
            # },
            'H121' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:40,slots:2;path=a:0,b:_0;path=a:2,b:_0;path=a:4,b:_0;label=H;upgrade=cost:80,terrain:water',
            },
            'L118' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:40,loc:5.5;city=revenue:40,loc:3.5;path=a:0,b:_0;path=a:5,b:_0;path=a:3,b:_1;path=a:4,b:_1;label=OO',
            },
            'L212' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:50,loc:5.5;city=revenue:50,loc:2.5;path=a:0,b:_0;path=a:5,b:_0;path=a:2,b:_1;path=a:3,b:_1;label=OO',
            },
            'L35' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:40;city=revenue:40;path=a:0,b:_0;path=a:2,b:_0;path=a:1,b:_1;path=a:5,b:_1;label=OO',
            },
            'L36' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:50;city=revenue:50;path=a:0,b:_0;path=a:4,b:_0;path=a:1,b:_1;path=a:3,b:_1;label=OO',
            },
            'L64' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:40;city=revenue:40,loc:3.5;path=a:0,b:_0;path=a:2,b:_0;path=a:3,b:_1;path=a:4,b:_1;label=OO',
            },
            'L65' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:40;city=revenue:40,loc:4.5;path=a:0,b:_0;path=a:2,b:_0;path=a:4,b:_1;path=a:5,b:_1;label=OO',
            },
            'L66' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:40;city=revenue:40,loc:1.5;path=a:0,b:_0;path=a:3,b:_0;path=a:1,b:_1;path=a:2,b:_1;label=OO',
            },
            'L67' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:40;city=revenue:40;path=a:0,b:_0;path=a:3,b:_0;path=a:1,b:_1;path=a:5,b:_1;label=OO',
            },
            'L68' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:40;city=revenue:40;path=a:0,b:_0;path=a:3,b:_0;path=a:2,b:_1;path=a:5,b:_1;label=OO',
            },
            'R121' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:40,slots:2;path=a:0,b:_0;path=a:2,b:_0;path=a:4,b:_0;label=R;upgrade=cost:80,terrain:water',
            },
            'R123' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:40,slots:2;path=a:0,b:_0;path=a:1,b:_0;path=a:2,b:_0;label=R;upgrade=cost:80,terrain:water',
            },
            'U121' => {
              'count' => 1,
              'color' => 'green',
              'code' => 'city=revenue:40,slots:2;path=a:0,b:_0;path=a:2,b:_0;path=a:4,b:_0;label=U;upgrade=cost:80,terrain:water',
            },
            'A62' => {
              'count' => 1,
              'color' => 'brown',
              'code' => 'city=revenue:80,slots:2;city=revenue:80,slots:2,loc:4;path=a:0,b:_0;path=a:1,b:_0;path=a:2,b:_0;'\
                        'path=a:3,b:_1;path=a:4,b:_1;path=a:5,b:_1;label=A;upgrade=cost:80,terrain:water',
            },
            'B545' => {
              'count' => 1,
              'color' => 'brown',
              'code' => 'city=revenue:40,slots:3;path=a:0,b:_0;path=a:2,b:_0;path=a:3,b:_0;path=a:4,b:_0;path=a:5,b:_0;label=B;upgrade=cost:80,terrain:water',
            },
            'B582' => {
              'count' => 1,
              'color' => 'brown',
              'code' => 'city=revenue:50,slots:2;path=a:0,b:_0;path=a:2,b:_0;path=a:3,b:_0;path=a:4,b:_0;label=B;upgrade=cost:80,terrain:water',
            },
            'H545' => {
              'count' => 1,
              'color' => 'brown',
              'code' => 'city=revenue:40,slots:3;path=a:0,b:_0;path=a:2,b:_0;path=a:3,b:_0;path=a:4,b:_0;path=a:5,b:_0;label=H;upgrade=cost:80,terrain:water',
            },
            'H582' => {
              'count' => 1,
              'color' => 'brown',
              'code' => 'city=revenue:50,slots:2;path=a:0,b:_0;path=a:2,b:_0;path=a:3,b:_0;path=a:4,b:_0;label=H;upgrade=cost:80,terrain:water',
            },
            'R545' => {
              'count' => 1,
              'color' => 'brown',
              'code' => 'city=revenue:40,slots:3;path=a:0,b:_0;path=a:2,b:_0;path=a:3,b:_0;path=a:4,b:_0;path=a:5,b:_0;label=R;upgrade=cost:80,terrain:water',
            },
            'R582' => {
              'count' => 1,
              'color' => 'brown',
              'code' => 'city=revenue:50,slots:2;path=a:0,b:_0;path=a:2,b:_0;path=a:3,b:_0;path=a:4,b:_0;label=R;upgrade=cost:80,terrain:water',
            },
            'U545' => {
              'count' => 1,
              'color' => 'brown',
              'code' => 'city=revenue:40,slots:3;path=a:0,b:_0;path=a:2,b:_0;path=a:3,b:_0;path=a:4,b:_0;path=a:5,b:_0;label=U;upgrade=cost:80,terrain:water',
            },
            'U582' => {
              'count' => 1,
              'color' => 'brown',
              'code' => 'city=revenue:50,slots:2;path=a:0,b:_0;path=a:2,b:_0;path=a:3,b:_0;path=a:4,b:_0;label=U;upgrade=cost:80,terrain:water',
            },
            'L339' => {
              'count' => 1,
              'color' => 'brown',
              'code' => 'city=revenue:50;city=revenue:50;path=a:0,b:_0;path=a:2,b:_0;path=a:3,b:_0;path=a:1,b:_1;path=a:4,b:_1;path=a:5,b:_1;label=OO',
            },
            'A456' => {
              'count' => 1,
              'color' => 'gray',
              'code' => 'city=revenue:100,slots:4;path=a:0,b:_0;path=a:1,b:_0;path=a:2,b:_0;path=a:3,b:_0;path=a:4,b:_0;path=a:5,b:_0;label=A',
            },
            'B176' => {
              'count' => 1,
              'color' => 'gray',
              'code' => 'city=revenue:60,slots:3;path=a:0,b:_0;path=a:1,b:_0;path=a:2,b:_0;path=a:3,b:_0;path=a:4,b:_0;path=a:5,b:_0;label=B',
            },
            'B512' => {
              'count' => 1,
              'color' => 'gray',
              'code' => 'city=revenue:70,slots:2;path=a:0,b:_0;path=a:2,b:_0;path=a:3,b:_0;path=a:4,b:_0;path=a:5,b:_0;label=B',
            },
            'H176' => {
              'count' => 1,
              'color' => 'gray',
              'code' => 'city=revenue:60,slots:3;path=a:0,b:_0;path=a:1,b:_0;path=a:2,b:_0;path=a:3,b:_0;path=a:4,b:_0;path=a:5,b:_0;label=H',
            },
            'H512' => {
              'count' => 1,
              'color' => 'gray',
              'code' => 'city=revenue:70,slots:2;path=a:0,b:_0;path=a:2,b:_0;path=a:3,b:_0;path=a:4,b:_0;path=a:5,b:_0;label=H',
            },
            'U176' => {
              'count' => 1,
              'color' => 'gray',
              'code' => 'city=revenue:60,slots:3;path=a:0,b:_0;path=a:1,b:_0;path=a:2,b:_0;path=a:3,b:_0;path=a:4,b:_0;path=a:5,b:_0;label=U',
            },
            'U512' => {
              'count' => 1,
              'color' => 'gray',
              'code' => 'city=revenue:70,slots:2;path=a:0,b:_0;path=a:2,b:_0;path=a:3,b:_0;path=a:4,b:_0;path=a:5,b:_0;label=U',
            },
            'R990' => {
              'count' => 1,
              'color' => 'gray',
              'code' => 'city=revenue:60,slots:4;path=a:0,b:_0;path=a:1,b:_0;path=a:2,b:_0;path=a:3,b:_0;path=a:4,b:_0;path=a:5,b:_0;label=R',
            },
            'R86' => {
              'count' => 1,
              'color' => 'gray',
              'code' => 'city=revenue:100,slots:3;path=a:0,b:_0;path=a:2,b:_0;path=a:3,b:_0;path=a:4,b:_0;path=a:5,b:_0;label=R',
            },
            'L340' => {
              'count' => 2,
              'color' => 'gray',
              'code' => 'city=revenue:60;city=revenue:60;path=a:0,b:_0;path=a:2,b:_0;path=a:3,b:_0;path=a:1,b:_1;path=a:4,b:_1;path=a:5,b:_1;path=a:_0,b:_1;label=OO',
            },
          }.freeze

          LOCATION_NAMES = {
            'A16' => 'Lauwersoog',
            'A20' => 'Overzeesch',
            'B13' => 'Leeuwarden',
            'B17' => 'Drachten & Surhuisterveen',
            'B19' => 'Groningen',
            'C12' => 'Sneek',
            'C18' => 'Roden & Assen',
            'C20' => 'Bremen',
            'D7' => 'Den Helder',
            'D15' => 'Heerenveen',
            'D19' => 'Emmen',
            'E10' => 'Hoorn',
            'E12' => 'Noordzee',
            'E14' => 'Zwolle',
            'E18' => 'Coevorden & Sleen',
            'F7' => 'Beverwijk & Zaandam',
            'F11' => 'Overzeesch',
            'F13' => 'Almere & Lelystad',
            'F19' => 'Rijseen & Almelo',
            'F21' => 'Oldenzaal',
            'G4' => 'Scheveningen',
            'G8' => 'Haarlem',
            'G10' => 'Amsterdam',
            'G14' => 'Harderwijk',
            'G16' => 'Apeldoorn & Deventer',
            'G18' => 'Hengelo & Enschede',
            'G20' => 'Hannover',
            'H5' => 'Den Haag',
            'H7' => 'Leiden & Delft',
            'H11' => 'Aalsmeer & Hilversum',
            'H13' => 'Amersfoort',
            'H17' => 'Zutphen & Doetinchem',
            'I8' => 'Gouda',
            'I12' => 'Utrecht',
            'I14' => 'Oss & Nijmegen',
            'I16' => 'Arnhem',
            'J7' => 'Rotterdam',
            'J17' => 'Ruhrgebied',
            'J17' => 'Ruhrgebied',
            'K2' => 'Hoek van Holland',
            'K4' => 'Goes',
            'K6' => 'Bergen op Zoom',
            'K8' => 'Breda',
            'K12' => 'Tilburg & Eindhoven',
            'K16' => 'Venlo',
            'L1' => 'Overzeesch',
            'L3' => 'Middelburg',
            'L5' => 'Hulst',
            'L7' => 'Essen',
            'L9' => 'Antwerpen',
            'L13' => 'Weert',
            'L17' => 'Roermond',
            'L19' => 'Mönchengladbach',
            'M2' => 'Brugge',
            'M4' => 'Teneuzen',
            'M10' => 'Neerpelt',
            'M16' => 'Sittard',
            'N13' => 'Geleen',
            'N15' => 'Maastricht',
            'N17' => 'Heerlen',
            'N19' => 'Aken & Keulen',
            'O14' => 'Luik',
            'O16' => 'Sint Geertruid',
          }.freeze

          HEXES = {
            white: {
              %w[A14 A18 B15 C14 C16 D17 E16 F9 F17 G6 H9 H19 I6 I10 I18 J13 K10 K14] => '',
              %w[D13 H15 J9 J11 J15 M14] => 'upgrade=cost:80,terrain:water',
              %w[D19 H13 I8 L3 N17] => 'city=revenue:0',
              %w[H5 I16 K6 K16 N15] => 'city=revenue:0;upgrade=cost:80,terrain:water',
              %w[B17 F19 G16 K12] => 'city=revenue:0;city=revenue:0;label=OO',
              %w[C18 E18 F7 H11 H17 I14] => 'town=revenue:0;town=revenue:0',
              %w[A16 D15 M16] => 'town=revenue:0',
              ['B13'] => 'city=revenue:0;border=edge:1,type:water',
              ['C12'] => 'town=revenue:0;border=edge:1,type:water;border=edge:2,type:water',
              ['E8'] => 'border=edge:3,type:water',
              ['E14'] => 'city=revenue:0;border=edge:0,type:water',
              ['F13'] => 'town=revenue:10;town=revenue:0;path=a:0,b:_0;'\
                         'border=edge:0,type:water;border=edge:3,type:water;border=edge:4,type:water;border=edge:5,type:water',
              ['F15'] => 'upgrade=cost:80,terrain:water;border=edge:1,type:water',
              ['G8'] => 'city=revenue:0;label=H;stub=edge:4;upgrade=cost:80,terrain:water',
              ['G14'] => 'city=revenue:0;border=edge:2,type:water',
              ['G18'] => 'city=revenue:0;city=revenue:0;label=OO;upgrade=cost:80,terrain:water',
              ['H7'] => 'town=revenue:0;town=revenue:0;upgrade=cost:80,terrain:water',
              ['I12'] => 'city=revenue:0;label=U;upgrade=cost:80,terrain:water',
              ['J7'] => 'city=revenue:0;label=R;stub=edge:3;upgrade=cost:80,terrain:water;border=edge:5,type:water',
              ['K8'] => 'city=revenue:0;label=B;path=a:5,b:_0;stub=edge:3;upgrade=cost:80,terrain:water;border=edge:2,type:water',
            },
            yellow: {
              %w[L13 L17] => 'city=revenue:20;path=a:1,b:_0;path=a:4,b:_0',
              ['B11'] => 'path=a:0,b:4;border=edge:4,type:water;border=edge:5,type:water',
              ['B19'] => 'city=revenue:20,slots:2;path=a:0,b:_0;path=a:1,b:_0',
              ['C10'] => 'path=a:0,b:3;border=edge:4,type:water',
              ['D9'] => 'path=a:1,b:3;border=edge:0,type:water;border=edge:1,type:water;border=edge:5,type:water',
              ['G10'] => 'city=revenue:40;city=revenue:40;label=A;path=a:1,b:_0;path=a:5,b:_1;upgrade=cost:80,terrain:water',
              ['G12'] => 'path=a:1,b:3;border=edge:3,type:water',
              ['L11'] => 'path=a:0,b:4',
              ['L15'] => 'path=a:1,b:4',
            },
            gray: {
              %w[M4 M10 O16] => 'town=revenue:10;path=a:2,b:_0;path=a:3,b:_0',
              ['B21'] => 'path=a:1,b:2;path=a:0,b:1',
              ['D7'] => 'town=revenue:10;path=a:4,b:_0;path=a:5,b:_0;border=edge:4,type:water',
              ['E10'] => 'city=revenue:40;path=a:0,b:_0;path=a:1,b:_0;path=a:2,b:_0;path=a:4,b:_0;border=edge:2,type:water',
              ['F21'] => 'town=revenue:10;path=a:0,b:_0;path=a:1,b:_0',
              ['G4'] => 'town=revenue:10;path=a:5,b:_0',
              ['I4'] => 'path=a:0,b:3;path=a:3,b:5',
              ['J3'] => 'path=a:0,b:3;path=a:0,b:4',
              ['J5'] => 'path=a:1,b:4;path=a:2,b:4',
              ['K2'] => 'town=revenue:20;path=a:0,b:_0;path=a:3,b:_0',
              ['K4'] => 'town=revenue:10;path=a:4,b:_0;path=a:5,b:_0',
              ['L5'] => 'town=revenue:10;path=a:1,b:2;path=a:0,b:_0;path=a:3,b:4;path=a:4,b:_0',
              ['L7'] => 'town=revenue:20;path=a:1,b:4;path=a:1,b:_0;path=a:3,b:_0',
              ['N13'] => 'town=revenue:10;path=a:3,b:_0;path=a:4,b:_0',
            },
            blue: {
              ['A20'] => 'offboard=revenue:yellow_20|brown_0|gray_100;path=a:0,b:_0;path=a:1,b:_0',
              ['D11'] => '',
              ['E12'] => 'offboard=revenue:yellow_20|brown_0|gray_10;path=a:1,b:_0;path=a:5,b:_0',
              ['F11'] => 'offboard=revenue:yellow_30|brown_0|gray_70;path=a:0,b:_0;path=a:5,b:_0',
              ['L1'] => 'offboard=revenue:yellow_30|brown_0|gray_100;path=a:3,b:_0;path=a:4,b:_0',
            },
            red: {
              ['L9'] => 'offboard=revenue:yellow_30|brown_20|gray_60;path=a:1,b:_0;path=a:2,b:_0;path=a:5,b:_0',
              ['M2'] => 'offboard=revenue:yellow_30|brown_20|gray_50;path=a:3,b:_0',
              ['O14'] => 'offboard=revenue:yellow_20|brown_30|gray_50;path=a:3,b:_0',
            },
            orange: {
              ['C20'] => 'offboard=revenue:yellow_20|brown_40|gray_60,groups:Bremen;path=a:1,b:_0;path=a:2,b:_0;path=a:3,b:_0;border=edge:5',
              ['D21'] => 'offboard=revenue:yellow_20|brown_40|gray_60,hide:1,groups:Bremen;path=a:1,b:_0;border=edge:2',
              ['G20'] => 'offboard=revenue:yellow_20|brown_40|gray_50;path=a:0,b:_0;path=a:1,b:_0;path=a:2,b:_0;path=a:3,b:_0',
              ['J17'] => 'offboard=revenue:0,groups:Ruhrgebied;icon=image:1839/ruhrgebied;path=a:0,b:_0;path=a:1,b:_0;path=a:2,b:_0;border=edge:5',
              ['K18'] => 'offboard=revenue:0,hide:1,groups:Ruhrgebied;path=a:1,b:_0;border=edge:2',
              ['L19'] => 'offboard=revenue:yellow_10|brown_20|gray_30;path=a:1,b:_0',
              ['N19'] => 'offboard=revenue:yellow_20|brown_40|gray_50;path=a:1,b:_0',
            }
          }.freeze
        end
      end
    end
  end